name: "Nullplatform Metadata"
description: "Github Action for query Nullplatform metadata"
inputs:
  resource:
    description: "nullplatform resource to query"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
