name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    env:
      INPUT_ACCESS-TOKEN: ${{ secrets.NULLPLATFORM_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          access-token: ${{ secrets.NULLPLATFORM_ACCESS_TOKEN }}
